
import "./globals.css";
import Image from "next/image";

import logo from "./assets/koolites_logo.jpg"
import Form from "@/components/Form";

export const metadata = {
  title: "Koolites Changing Lives",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        <section className="sticky top-0 lg:h-[120px] h-[90px] z-[1000]  bg-white shadow-lg shadow-neutral-800 flex justify-center items-center">
          <div className="container ">
            <div className="flex justify-between items-center ">
              <div className="">
                <Image alt="oolites logo" src={logo} className="lg:h-[120px] lg:w-[170px] h-[70px] w-[100px]"/>
              </div>
              <div className="">
                <ul className="flex gap-5 text-blue-500 head-ul lg:text-[20px] text-[12px] lg:mr-0 mr-5">
                  <li><a href="#aboutus">About Us</a></li>
                  <li><a href="#ourteam">Our Team</a></li>
                  <li><a href="#projects">Projects</a></li>
                  <li><a href="#events">Events</a></li>
                  <li><a href="#contact">Contact Us</a></li>
                </ul>
              </div>
            </div>
          </div>
        </section>
        {children}
        <footer id="contact" className="bg-blue-500 flex  justify-center items-center py-[60px]">
          <div className="container">
            <div className="flex lg:flex-row flex-col lg:gap-0 gap-5 items-center justify-between ">
              <div className="">
                <Image alt="koolites logo" src={logo} height={100} width={150}/>
              </div>
              <Form/>
              <div className="">
                <ul className="flex flex-col gap-4">
                  <li><u>Useful Links</u></li>
                  <li><a href="#aboutus">About Us</a></li>
                  <li><a href="#ourteam">Our Team</a></li>
                  <li><a href="#events">Events</a></li>
                  <li><a href="#contact">Contact Us</a></li>
                </ul>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
