
import "./globals.css";
import Image from "next/image";

import logo from "./assets/koolites_logo.jpg"

export const metadata = {
  title: "Koolites Changing Lives",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        <section className="sticky top-0 lg:h-[150px] h-[90px] z-[1000] bg-white shadow-lg shadow-neutral-800 flex justify-center items-center">
          <div className="container ">
            <div className="flex justify-between items-center ">
              <div className="">
                <Image alt="oolites logo" src={logo} className="lg:h-[150px] lg:w-[200px] h-[70px] w-[100px]"/>
              </div>
              <div className="">
                <ul className="flex gap-5 text-blue-500 head-ul lg:text-[20px] text-[12px] lg:mr-0 mr-5">
                  <li><a href="#aboutus">About Us</a></li>
                  <li><a href="#ourteam">Our Team</a></li>
                  <li><a href="#events">Events</a></li>
                  <li><a href="#contact">Contact Us</a></li>
                </ul>
              </div>
            </div>
          </div>
        </section>
        {children}
        <footer className="bg-blue-500 flex  justify-center items-center py-[60px]">
          <div className="container">
            <div className="flex lg:flex-row flex-col lg:gap-0 gap-5 items-center justify-between ">
              <div className="">
                <ul className="flex flex-col gap-4">
                  <li><u>Useful Links</u></li>
                  <li><a href="#aboutus">About Us</a></li>
                  <li><a href="#ourteam">Our Team</a></li>
                  <li><a href="#events">Events</a></li>
                  <li><a href="#contact">Contact Us</a></li>
                </ul>
              </div>
              <div className="">
                <Image alt="koolites logo" src={logo} height={200} width={250}/>
              </div>
              <div className="flex flex-col items-center gap-2">
                <h2>Contact Us</h2>
                <form className="flex flex-col items-center gap-1 footer-form">
                  <input type="text" placeholder="Enter your Name"/>
                  <input type="text" placeholder="Enter your Organization"/>
                  <input type="tel" placeholder="Enter your Phone Number" />
                  <input type="email" placeholder="Enter your Email"/>
                  <textarea placeholder="enter your message"></textarea>
                  <button type="submit">Send Message</button>
                </form> 
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
